databases:
  - name: budgetordb
    plan: free
    databaseName: budgetor
    user: budgetor

services:
  - type: web
    plan: free
    name: budgetor
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn budgetor.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetordb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4